version: "3.9"

services:
  nextapp:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install -g pnpm && pnpm install && pnpm build && pnpm start"
    environment:
      - NODE_ENV=production
